# ---------------------------------------
# Fenn Configuration (Modify Carefully)
# ---------------------------------------

project: vgg

logger:
  dir: logger

# ---------------------------------------
# User Section
# ---------------------------------------
general:
  device: cuda

model:
  in_channels: 3
  num_classes: 10

train:
  seed: 42
  batch: 32
  epochs: 1
  lr: 1e-3

test:
  size: 0.2
  batch: 32

dataset:
  dir: data