# ---------------------------------------
# Fenn Configuration (Modify Carefully)
# ---------------------------------------

project: mlp

logger:
  dir: logger

# ---------------------------------------
# User Section
# ---------------------------------------
general:
  device: cuda

train:
  seed: 42
  batch: 16
  epochs: 50
  lr: 4e-3

val:
  size: 0.2
  batch: 16
  epoch: 5

test:
  size: 0.2
  batch: 16
